# Generated by Django 4.2.4 on 2023-09-13 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConsumers',
            fields=[
                ('channel_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knox.authtoken', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
