# Generated by Django 4.2.4 on 2023-09-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_clientconsumers_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='seen_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
