# Generated by Django 4.2.4 on 2023-08-21 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyPhoneNUmber',
            fields=[
                ('phone', models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must start with a plus sign (+) and consist of digits only.', regex='^\\+[\\d]+$')])),
                ('ip_address', models.CharField(max_length=15)),
            ],
        ),
    ]
