# Generated by Django 4.2.4 on 2023-08-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
