# Generated by Django 4.2.4 on 2023-08-21 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_id_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must start with a plus sign (+) and consist of digits only.', regex='^\\+[\\d]+$')]),
        ),
    ]
