# Generated by Django 4.2.4 on 2023-08-21 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verifyphonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyPhoneNUmber',
        ),
    ]
