# Generated by Django 4.2.4 on 2023-08-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_phonetokentempmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
